### ISSUE TITLE
Better handling of article posting

### ISSUE THREAD

**Issue by sardred** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-48#16]
As of right now, you get thrown to the login page, which doesn't make any sense as you're already logged in.
If you throw right back to add-article, there's no feedback given in response to pressing the button for adding, and the fields don't empty, so you can spam the button basically posting the exact same article over and over.

TL;DR:
- [x] Route back to add-article with cleared input and new feedback when posting an article.
- [ ] Add validation for duplicate articles

**Comment by ivarflakstad** [comment]
What should such validation entail?
I am thinking no duplicate titles per user.
